### ISSUE TITLE
user session still keeps 'admin' anonymous session

### ISSUE THREAD

**Issue by peidong-hu** [cuba-platform/sample-portal#3]
Hi,

I am debugging this sample, by inject UserSessionSource into the MenuController. The .getUserSession().getUser() always returns the admin anonymous portal session, even I have logged in the portal with 'demo' user successfully.

Here is the code to inspect this,
@Controller
public class MenuController {

    protected Logger log = LoggerFactory.getLogger(getClass());

    @Inject
    private UserSessionSource usSource; 
    @Inject
    protected ConversionFactory conversionFactory;

    @Inject
    protected DataService dataService;

    @Inject
    protected Metadata metadata;

    @CrossOrigin(origins = "*")
    @RequestMapping(value = "/menu", method = RequestMethod.GET)
    @ResponseBody
    public String menu() {
    	User user = usSource.getUserSession().getUser();
        LoadContext<MenuItem> foodLoadContext = new LoadContext<>(MenuItem.class)
            .setQuery(LoadContext.createQuery("select u from demo$MenuItem u"))
            .setView(View.LOCAL);

        List<MenuItem> entities = dataService.loadList(foodLoadContext);
        MetaClass metaClass = metadata.getClassNN(MenuItem.class);

        Converter converter = conversionFactory.getConverter("json");

        try {
            return converter.process((List) entities, metaClass, foodLoadContext.getView());
        } catch (Exception e) {
            log.error("Error converting json", e);
            return "";
        }
    }
}

**Comment by peidong-hu** [comment]
![2017-10-16-153254_1920x1848_scrot](https://user-images.githubusercontent.com/7647371/31631347-796237e2-b287-11e7-9179-fa369d748693.png)

**Comment by jreznot** [comment]
Hi,

It is OK, since the controller is created as Portal controller and it knows nothing about user logged in to REST-API. In fact, when you log in - you will be logged in to REST-API and to the portal application. If you want to use security information of user, I'd recommend that you create a custom controller as REST-API controller: https://doc.cuba-platform.com/manual-6.6/rest_api_v2_custom_controllers.html

**Comment by peidong-hu** [comment]
Do we have an example that shows how oauth2 based login works in angularjs
with rest api v2?

**Comment by jreznot** [comment]
You can find a simple example of login to REST-API with JavaScript here: https://doc.cuba-platform.com/manual-6.6/rest_api_v2_ex_javascript_usage.html I think that you can use the same code with Angular JS with slight modifications

**Comment by peidong-hu** [comment]
Thanks, very helpful.

Peidong
